Sprint 4
Elvehnn/middle.messenger.praktikum.yandex pull request #5
Opened 2022-11-12 15:33 UTC by Elvehnn

Выполнено задание 4 спринта:
1. Написаны тесты для компонентов Button, ChatItem, страниц signin и profile, классов Router и Store. Для их выполнения созданы моковые данные и некоторые утилиты в папке ./src/testUtils, в т.ч. мок для API.
Для тестирования используется Jest по рекомендации и с разрешения наставников курса. Тесты для шаблонизатора отсутствуют, т.к. в проекте используется Handlebars.
2. Настроена сборка с помощью Webpack. 
3. Проект задеплоен на netlify - https://chat-messanger-elvehnn.netlify.app/.
4. Настроена сборка Docker-контейнера (описание скрипта запуска - в readme). Контейнер задеплоен на heroku - https://frozen-hamlet-15688.herokuapp.com/.
5. Настроен precommit с помощью huskey  и lint-staged.
6. Проведен аудит пакетов.

2022-11-13 13:27 UTC, podlovchenko requested changes
Привет, спасибо за подробный комментарий к пулл реквесту 👍 
Есть несколько замечаний по работе системы и проекту
1. Не проходит регулярка для такого значения телефона, хотя должна 
<img width="602" alt="Снимок экрана 2022-11-13 в 16 04 14" src="https://user-images.githubusercontent.com/22602747/201523355-d2a814ed-29e6-41b6-bc13-7b64119e029a.png">
2. При пустом значении displayName отображается {{data}}
<img width="594" alt="Снимок экрана 2022-11-13 в 16 05 11" src="https://user-images.githubusercontent.com/22602747/201523400-39506ddd-978b-49dc-8822-e583db5819db.png">
3. Не получается выбрать сообщение и проверить работу чата
4. Есть ошибки линтера
5. Почти в каждом файле есть отключение линтера, стоит настроить его под себя

2022-11-13 13:27 UTC, podlovchenko commented on src/core/Block.ts
>      return true;
В этом методе всегда вернется true

2022-11-13 13:27 UTC, podlovchenko commented on src/core/Block.ts
> +    // console.log('set new prop', this.id, this.constructor.name, nextPartialProps);
Будет классно почистить проект от уже ненужного закомментированного кода

2022-11-13 22:23 UTC, Elvehnn commented on src/core/Block.ts
> +    // console.log('set new prop', this.id, this.constructor.name, nextPartialProps);
Done

2022-11-14 10:57 UTC, Elvehnn commented on src/core/Block.ts
>      return true;
По умолчанию так и было задумано, всегда перерендеривать. Доработал, теперь пропсы сравниваются и лишний рендер не выполняется

2022-11-14 13:42 UTC, Elvehnn commented
Доброго часа! Спасибо большое за ревью! Пропустила, что отвалился сам чат  - поторопилась( 
Отправку сообщений пофиксила. Плюсом добавила пингование для поддержки чата живым.
С линтером почти все поправила, некоторые ошибки заменила на warnings, особенно в Block и RegisterComponent - буду еще копать и разбираться. В SocketController логирование оставила - буду добавлять уведомления.
И остальные замечания исправила.

2022-11-14 14:45 UTC, podlovchenko commented
Привет, спасибо за оперативные правки, сейчас есть замечание по работе чата, не подгружается история сообщений

2022-11-15 10:00 UTC, podlovchenko commented
Работу примаю)

2022-11-15 10:02 UTC, Elvehnn commented
Вера, спасибо, что помогла сделать работу лучше!

2022-11-29 19:23 UTC, merged